// export const STUDENT_RESPONSE_SHEET_REQUEST = 'STUDENT_RESPONSE_SHEET_REQUEST';
// export const STUDENT_RESPONSE_SHEET_SUCCESS = 'STUDENT_RESPONSE_SHEET_SUCCESS';
// export const STUDENT_RESPONSE_SHEET_FAIL = 'STUDENT_RESPONSE_SHEET_FAIL';

// export const STUDENT_ANSWER_REQUEST = 'STUDENT_ANSWER_REQUEST';
// export const STUDENT_ANSWER_SUCCESS = 'STUDENT_ANSWER_SUCCESS';
// export const STUDENT_ANSWER_FAIL = 'STUDENT_ANSWER_FAIL';
