export const STUDENT_RESPONSE_SHEET_REQUEST = 'STUDENT_RESPONSE_SHEET_REQUEST';
export const STUDENT_RESPONSE_SHEET_SUCCESS = 'STUDENT_RESPONSE_SHEET_SUCCESS';
export const STUDENT_RESPONSE_SHEET_FAIL = 'STUDENT_RESPONSE_SHEET_FAIL';
