export const STUDENT_REGISTRATION_REQUEST = 'STUDENT_REGISTRATION_REQUEST';
export const STUDENT_REGISTRATION_SUCCESS = 'STUDENT_REGISTRATION_SUCCESS';
export const STUDENT_REGISTRATION_FAIL = 'STUDENT_REGISTRATION_FAIL';
