export const STUDENT_REGISTRATION_REQUEST = 'STUDENT_REGISTRATION_REQUEST';
export const STUDENT_REGISTRATION_SUCCESS = 'STUDENT_REGISTRATION_SUCCESS';
export const STUDENT_REGISTRATION_FAIL = 'STUDENT_REGISTRATION_FAIL';

export const REGISTRATION_OPEN_SUCCESS = 'REGISTRATION_OPEN_SUCCESS';
export const REGISTRATION_OPEN_FAIL = 'REGISTRATION_OPEN_FAIL';

export const REGISTRATION_CLOSE_SUCCESS = 'REGISTRATION_CLOSE_SUCCESS';
export const REGISTRATION_CLOSE_FAIL = 'REGISTRATION_CLOSE_FAIL';
