export const SUPERVISOR_LIST_REQUEST = 'SUPERVISOR_LIST_REQUEST';
export const SUPERVISOR_LIST_SUCCESS = 'SUPERVISOR_LIST_SUCCESS';
export const SUPERVISOR_LIST_FAIL = 'SUPERVISOR_LIST_FAIL';

export const SUPERVISOR_REQ_LIST_REQUEST = 'SUPERVISOR_REQ_LIST_REQUEST';
export const SUPERVISOR_REQ_LIST_SUCCESS = 'SUPERVISOR_REQ_LIST_SUCCESS';
export const SUPERVISOR_REQ_LIST_FAIL = 'SUPERVISOR_REQ_LIST_FAIL';

export const SUPERVISOR_UPDATEPERM_REQUEST = 'SUPERVISOR_UPDATEPERM_REQUEST';
export const SUPERVISOR_UPDATEPERM_SUCCESS = 'SUPERVISOR_UPDATEPERM_SUCCESS';
export const SUPERVISOR_UPDATEPERM_FAIL = 'SUPERVISOR_UPDATEPERM_FAIL';
